#!/bin/bash

awk '/#! @BeginExampleSession/{ f=1; next } /#! @EndExampleSession/{ f=0 } f' $1 > tst/uncut_examples.tst

cut -c4- tst/uncut_examples.tst > $2
rm tst/uncut_examples.tst

####################################################################
# To run this, cd into the main folder for the package and run:
#
# $ ./extracttests lib/<file>.gd tst/<outfile>.tst # create testfile
# gap loadpackage.g
# gap> Test("tst/<outfile>.tst");
#
####################################################################

