#############################################################################
##
#W  subquotient.gd          WeylModules GAP package              S.R. Doty
##
##  This file contains declarations for submodules of quotient Weyl modules.
##
#############################################################################


#! @ChapterInfo Weyl_modules, Filters
#! @Arguments V
#! @Group IsSubQuotientWeylModule
DeclareCategory( "IsSubQuotientWeylModule", 
  CategoryCollections(IsLeftAlgebraModuleElement) );


DeclareOperation( "IsWithin", 
            [IsSubQuotientWeylModule,IsLeftAlgebraModuleElement]);

#! @ChapterInfo Weyl_modules, Constructors
#! @Description
#! The first form constructs the submodule of the given quotient 
#! Weyl module <A>Q</A> generated by the given element <A>v</A>.
#! @Returns a SubQuotientWeylModule
#! @Arguments Q,v
#! @Group SubQuotientWeylModule
DeclareOperation( "SubWeylModule", 
            [IsQuotientWeylModule,IsLeftAlgebraModuleElement]);

#! @ChapterInfo Weyl_modules, Constructors
#! @Description
#! The second form constructs the subquotient Weyl module (of the 
#! ambient quotient) generated by the given subquotient <A>S</A> 
#! and given element <A>v</A>.
#! @Arguments S,v
#! @Group SubQuotientWeylModule
DeclareOperation( "SubWeylModule", 
            [IsSubQuotientWeylModule,IsLeftAlgebraModuleElement]);

#! @ChapterInfo Weyl_modules, Constructors
#! @Description
#! The third form constructs the submodule of the given quotient 
#! Weyl module <A>Q</A> generated by the given element <A>list</A> 
#! of elements.
#! @Arguments Q,list
#! @Group SubQuotientWeylModule
DeclareOperation( "SubWeylModule", [IsQuotientWeylModule,IsList]);

#! @ChapterInfo Weyl_modules, Constructors
#! @Description
#! The fourth form constructs the subquotient Weyl module generated
#! by the given subquotient <A>S</A> and given <A>list</A> of elements.
#! @Arguments S,list
#! @Group SubQuotientWeylModule
DeclareOperation( "SubWeylModule", [IsSubQuotientWeylModule,IsList]);

#! @ChapterInfo Weyl_modules, Constructors
#! @Description
#! The fifth form constructs the submodule of the quotient Weyl module <A>Q</A>
#! which is the direct sum of the given <A>list</A> of subquotients (which are
#! assumed to be linearly independent, without checking).
#! @Arguments Q,list
#! @Group SubQuotientWeylModule
DeclareOperation("SubWeylModuleDirectSum", [IsQuotientWeylModule,IsList]);


DeclareOperation("Generators", [IsSubQuotientWeylModule]);


DeclareOperation("BasisVecs", [IsSubQuotientWeylModule]);


DeclareAttribute("Dim", IsSubQuotientWeylModule );

#! @ChapterInfo Weyl_modules, Unique ops for subquotients
#! @Description
#! This function returns the ambient quotient Weyl module containing the given
#! subquotient <A>S</A>.
#! @Returns a QuotientWeylModule
#! @Arguments S
DeclareOperation("AmbientQuotient", [IsSubQuotientWeylModule]);


DeclareOperation("TheCharacteristic", [IsSubQuotientWeylModule]);


DeclareAttribute("TheLieAlgebra", IsSubQuotientWeylModule );


DeclareAttribute("Weights", IsSubQuotientWeylModule );


DeclareAttribute("DominantWeights", IsSubQuotientWeylModule );


DeclareAttribute("WeightSpaces", IsSubQuotientWeylModule );


DeclareAttribute("Character", IsSubQuotientWeylModule );


DeclareAttribute("DominantWeightSpaces", IsSubQuotientWeylModule );


DeclareOperation("WeightSpace", [IsSubQuotientWeylModule,IsList]);

#! @ChapterInfo Weyl_modules, Unique ops for quotients
#! @Description
#! This function returns the socle of the given quotient Weyl module
#! <A>Q</A>.
#! @Returns a SubQuotientWeylModule
#! @Arguments Q
DeclareAttribute("SocleWeyl", IsQuotientWeylModule );

#! @ChapterInfo Weyl_modules, Unique ops for subquotients
#! @Description
#! This function returns the maximal subquotient <A>T</A> containing 
#! the given subquotient <A>S</A> such that $T/S$ is semisimple. 
#! If <A>S</A> happens to be an element of the socle series then the 
#! function returns the next element in the socle series.
#! @Returns a SubQuotientWeylModule
#! @Arguments S
DeclareOperation("NextSocle", [IsSubQuotientWeylModule]);


DeclareAttribute("DecompositionNumbers", IsSubQuotientWeylModule );

